### ISSUE TITLE
Vagrant hostmanager plugin check always fails

### ISSUE THREAD

**Issue by flibbertigibbet** [opendataphilly/opendataphilly-ckan#77]
Despite having the plugin installed, attempting to run `vagrant up` in the project directory fails with:

`ERROR: vagrant-hostmanager not found; please run 'vagrant plugin install vagrant-hostmanager'`

**Comment by flibbertigibbet** [comment]
I am currently on the latest vagrant release, 2.1.4. This is the same issue as [this](https://github.com/azavea/cicero/issues/1506).

**Comment by rcheetham** [comment]
We are archiving this repository as the CKAN instance has been replaced and no new work is planned.
