### ISSUE TITLE
Create a health check for the Apache workers that restarts on failure

### ISSUE THREAD

**Issue by jeancochrane** [opendataphilly/opendataphilly-ckan#93]
Following up on our [December 3rd incident report](https://docs.google.com/document/d/1HdfB2QQWE6riJxRjzxy06klZqU4FrSJZ0C18_3i86JM/edit?usp=sharing) (#93): The surest way to prevent another application failure due to a race condition would be to configure a health check for Apache that can attempt to restart a worker in the case of failure. If the worker had been set to automatically restart during the December 3rd incident, the degraded service that we experienced would not have persisted for more than a few seconds.

We could accomplish this with a tool like [Monit](https://mmonit.com/monit/) or [supervisord](https://serversforhackers.com/c/monitoring-processes-with-supervisord).

**Comment by rcheetham** [comment]
We are archiving this repository as the CKAN instance has been replaced and no new work is planned.
