### ISSUE TITLE
Determine whether ckanext-pages is thread-safe

### ISSUE THREAD

**Issue by jeancochrane** [opendataphilly/opendataphilly-ckan#94]
It's possible that the `ckanex-pages` plugin is not thread-safe. We believe that this is may be the case based on an apparent race condition in two threads spawned by one worker, a race condition that seems to have caused a shared SQLAlchemy connection to enter a degraded state for that worker. For more background, see our investigation into https://github.com/azavea/opendataphilly-ckan/issues/92#issuecomment-443790310.

Based on discussion in https://github.com/ckan/ckanext-pages/issues/81, we should evaluate if this is true, and if there is any way for us to mitigate the issue in the ODP application.

**Comment by rcheetham** [comment]
We are archiving this repository as the CKAN instance has been replaced and no new work is planned.
